### ISSUE TITLE
error Running it locally

### ISSUE THREAD

**Issue by Bhirpara** [markfullmer/grammark#14]
![Screenshot (3)](https://user-images.githubusercontent.com/51133648/62232804-111b1f80-b395-11e9-8bd5-ce2b3dc59849.png)
![Screenshot (2)](https://user-images.githubusercontent.com/51133648/62232814-18422d80-b395-11e9-9fa4-61562f471cc2.png)
![Screenshot (1)](https://user-images.githubusercontent.com/51133648/62232823-1e380e80-b395-11e9-9461-90d5aba40469.png)

**Comment by rs9899** [comment]
I even have similar issues.

`npm install -g grunt-cli bower yo generator-karma generator-angular`
`npm install`

```
$ grunt serve
Loading "cdnify.js" tasks...ERROR
>> ReferenceError: primordials is not defined

Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue.

Aborted due to warnings.
```

**Comment by markfullmer** [comment]
Thanks for reporting this!

I've updated the instructions.
