### ISSUE TITLE
Bug (?) in sentence length computation

### ISSUE THREAD

**Issue by highkite** [markfullmer/grammark#19]
Hello,

I think there is an error in the sentence length checker.
In the `process(...)` function you call the `type.data.process(...)` function with the `this.spacedPunctuation` parameter.
https://github.com/markfullmer/grammark/blob/58f6d33667577690f4d974ae7b2fa07e6a230a25/app/scripts/app.js#L149

In the `sentences` function this is used in `getSentences(...)` to retrieve text split sentence wise.

https://github.com/markfullmer/grammark/blob/58f6d33667577690f4d974ae7b2fa07e6a230a25/app/scripts/models/sentences.js#L17

The problem is (potentially) the following line:

https://github.com/markfullmer/grammark/blob/58f6d33667577690f4d974ae7b2fa07e6a230a25/app/scripts/app.js#L135

here you replace ',' by '.' 

That means you count only the sentence length of subphrases or subsentences. Or is this intended behavior?

**Comment by markfullmer** [comment]
Thanks for identifying this. This looks like an unintentional behavior in the code. I'll try to address it soon.

**Comment by markfullmer** [comment]
After reviewing the code, I've determined there is no issue here. The `this.spacedPunctuation` value is not used in any way to count sentences. The sentence counter has its own parsing mechanism in `getSentences()`. The only place where `this.spacedPunctuation` is used is to tally up how many errors the checker found for each category.

If you still think there is a error in sentence length computation, can you provide sample sentences that demonstrate the problem?
